services:
  tensorflow:
    image: tensorflow/tensorflow:latest-jupyter
    container_name: tensorflow
    volumes:
      - ./notebooks:/tf/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=hwr